"use client";

import { useState } from "react";
import Link from "next/link";

interface SitemapEntry {
  id:          number;
  url:         string;
  priority:    string;
  changefreq:  string;
  lastmod:     string;
}

let nextId = 1;

const TODAY = new Date().toISOString().slice(0, 10);

const FREQ_OPTIONS = [
  { label: "Always",  value: "always"  },
  { label: "Hourly",  value: "hourly"  },
  { label: "Daily",   value: "daily"   },
  { label: "Weekly",  value: "weekly"  },
  { label: "Monthly", value: "monthly" },
  { label: "Yearly",  value: "yearly"  },
  { label: "Never",   value: "never"   },
];

const PRIORITY_OPTIONS = [
  { label: "1.0 — Highest (Homepage)", value: "1.0" },
  { label: "0.9 — Very High",          value: "0.9" },
  { label: "0.8 — High",               value: "0.8" },
  { label: "0.7 — Above Average",      value: "0.7" },
  { label: "0.6 — Slightly Above",     value: "0.6" },
  { label: "0.5 — Normal (default)",   value: "0.5" },
  { label: "0.4 — Slightly Below",     value: "0.4" },
  { label: "0.3 — Below Average",      value: "0.3" },
  { label: "0.1 — Lowest",            value: "0.1" },
];

export default function SitemapGeneratorClient() {
  const [domain, setDomain]   = useState("");
  const [bulkMode, setBulkMode] = useState(false);
  const [bulkText, setBulkText] = useState("");
  const [entries, setEntries] = useState<SitemapEntry[]>([
    { id: nextId++, url: "/",        priority: "1.0", changefreq: "daily",   lastmod: TODAY },
    { id: nextId++, url: "/about",   priority: "0.8", changefreq: "monthly", lastmod: TODAY },
    { id: nextId++, url: "/contact", priority: "0.7", changefreq: "monthly", lastmod: TODAY },
    { id: nextId++, url: "/blog",    priority: "0.9", changefreq: "daily",   lastmod: TODAY },
  ]);
  const [copied,     setCopied]     = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  function addEntry() {
    setEntries(prev => [...prev, {
      id: nextId++, url: "", priority: "0.5", changefreq: "weekly", lastmod: TODAY,
    }]);
  }

  function removeEntry(id: number) {
    setEntries(prev => prev.filter(e => e.id !== id));
  }

  function updateEntry(id: number, field: keyof Omit<SitemapEntry, "id">, value: string) {
    setEntries(prev => prev.map(e => e.id === id ? { ...e, [field]: value } : e));
  }

  function processBulk() {
    const lines = bulkText.split("\n").map(l => l.trim()).filter(Boolean);
    const newEntries: SitemapEntry[] = lines.map(line => {
      const path = line.startsWith("http") ? line : (domain ? line : "/" + line.replace(/^\//, ""));
      return { id: nextId++, url: path, priority: "0.5", changefreq: "weekly", lastmod: TODAY };
    });
    setEntries(newEntries);
    setBulkMode(false);
    setBulkText("");
  }

  function generateXML(): string {
    const base = domain.replace(/\/$/, "");
    const lines = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!-- Generated by PursTech Sitemap Generator -->',
      '<!-- https://purstech.com/tools/sitemap-generator -->',
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ];

    entries.forEach(entry => {
      const url = entry.url.startsWith("http") ? entry.url : `${base}${entry.url || "/"}`;
      lines.push("  <url>");
      lines.push(`    <loc>${url}</loc>`);
      if (entry.lastmod)   lines.push(`    <lastmod>${entry.lastmod}</lastmod>`);
      if (entry.changefreq) lines.push(`    <changefreq>${entry.changefreq}</changefreq>`);
      if (entry.priority)  lines.push(`    <priority>${entry.priority}</priority>`);
      lines.push("  </url>");
    });

    lines.push("</urlset>");
    return lines.join("\n");
  }

  const output = generateXML();

  function copy() {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function download() {
    const blob = new Blob([output], { type: "application/xml" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = "sitemap.xml";
    a.click();
    URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2000);
  }

  return (
    <div className="min-h-screen bg-[#0A0A14] text-white font-sans">

      <nav className="border-b border-white/5 px-4 py-4 sticky top-0 bg-[#0A0A14]/95 backdrop-blur-md z-40">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-xl font-black">Purs<span className="text-[#6C3AFF]">Tech</span></Link>
          <Link href="/tools" className="text-sm text-gray-500 hover:text-white transition-colors">All Tools</Link>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 py-10">

        <nav className="text-xs text-gray-600 mb-6 flex items-center gap-2">
          <Link href="/" className="hover:text-gray-400 transition-colors">Home</Link>
          <span>›</span>
          <Link href="/tools" className="hover:text-gray-400 transition-colors">Tools</Link>
          <span>›</span>
          <span className="text-gray-400">Sitemap Generator</span>
        </nav>

        <div className="mb-8">
          <div className="inline-flex items-center gap-2 bg-[#6C3AFF]/10 border border-[#6C3AFF]/20 rounded-full px-3 py-1 text-xs text-[#6C3AFF] font-semibold mb-3">
            SEO Tools
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-3">
            Free XML Sitemap Generator Online
          </h1>
          <p className="text-gray-400 max-w-2xl">
            Create a valid XML sitemap for your website in seconds. Set priority and change frequency for each URL, then download and submit to Google Search Console.
          </p>
        </div>

        {/* Domain */}
        <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5 mb-5">
          <label className="block text-sm font-semibold text-white mb-2">Website Domain</label>
          <input value={domain} onChange={e => setDomain(e.target.value)}
            placeholder="https://yoursite.com"
            className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
          <p className="text-xs text-gray-500 mt-1.5">Enter your domain so relative paths (like /about) become full URLs in the sitemap.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

          {/* URL Builder */}
          <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-white text-sm">
                URLs ({entries.length})
              </h3>
              <div className="flex gap-2">
                <button onClick={() => setBulkMode(!bulkMode)}
                  className="px-3 py-1.5 rounded-lg bg-[#0A0A14] border border-white/10 text-gray-400 hover:text-white text-xs transition-all">
                  {bulkMode ? "Single Mode" : "Bulk Import"}
                </button>
                <button onClick={addEntry}
                  className="px-3 py-1.5 rounded-lg bg-[#6C3AFF] hover:bg-[#5B2EE0] text-white text-xs font-bold transition-all">
                  + Add URL
                </button>
              </div>
            </div>

            {bulkMode ? (
              <div>
                <p className="text-xs text-gray-500 mb-2">Enter one URL or path per line:</p>
                <textarea value={bulkText} onChange={e => setBulkText(e.target.value)} rows={8}
                  placeholder={"/\n/about\n/contact\n/blog\n/blog/my-post"}
                  className="w-full px-4 py-3 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all resize-none font-mono" />
                <button onClick={processBulk}
                  className="mt-3 w-full py-2.5 rounded-xl bg-[#6C3AFF] hover:bg-[#5B2EE0] text-white text-sm font-bold transition-all">
                  Import URLs
                </button>
              </div>
            ) : (
              <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
                {entries.map(entry => (
                  <div key={entry.id} className="bg-[#0A0A14] rounded-xl p-3 border border-white/5">
                    <div className="flex items-center gap-2 mb-2">
                      <input value={entry.url} onChange={e => updateEntry(entry.id, "url", e.target.value)}
                        placeholder="/page-path or https://..."
                        className="flex-1 px-3 py-2 rounded-lg bg-[#13131F] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all font-mono" />
                      <button onClick={() => removeEntry(entry.id)}
                        className="text-gray-600 hover:text-[#FF3A6C] text-sm transition-colors flex-shrink-0">
                        ×
                      </button>
                    </div>
                    <div className="grid grid-cols-3 gap-2">
                      <select value={entry.priority}
                        onChange={e => updateEntry(entry.id, "priority", e.target.value)}
                        className="px-2 py-1.5 rounded-lg bg-[#13131F] border border-white/10 text-white text-xs focus:outline-none focus:border-[#6C3AFF]/60 transition-all">
                        {PRIORITY_OPTIONS.map(o => (
                          <option key={o.value} value={o.value}>{o.value}</option>
                        ))}
                      </select>
                      <select value={entry.changefreq}
                        onChange={e => updateEntry(entry.id, "changefreq", e.target.value)}
                        className="px-2 py-1.5 rounded-lg bg-[#13131F] border border-white/10 text-white text-xs focus:outline-none focus:border-[#6C3AFF]/60 transition-all">
                        {FREQ_OPTIONS.map(o => (
                          <option key={o.value} value={o.value}>{o.label}</option>
                        ))}
                      </select>
                      <input type="date" value={entry.lastmod}
                        onChange={e => updateEntry(entry.id, "lastmod", e.target.value)}
                        className="px-2 py-1.5 rounded-lg bg-[#13131F] border border-white/10 text-white text-xs focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Output */}
          <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5 flex flex-col">
            <div className="flex items-center justify-between mb-3">
              <div>
                <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider">sitemap.xml</h3>
                <span className="text-xs text-gray-600 mt-0.5 block">{entries.length} URLs</span>
              </div>
              <div className="flex gap-2">
                <button onClick={copy}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    copied ? "bg-green-600 text-white" : "bg-[#0A0A14] border border-white/10 text-gray-400 hover:text-white"
                  }`}>
                  {copied ? "✓ Copied!" : "Copy"}
                </button>
                <button onClick={download}
                  className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    downloaded ? "bg-green-600 text-white" : "bg-[#6C3AFF] hover:bg-[#5B2EE0] text-white"
                  }`}>
                  {downloaded ? "✓ Saved!" : "⬇ Download"}
                </button>
              </div>
            </div>
            <pre className="flex-1 text-xs text-green-400 bg-[#0A0A14] rounded-xl p-4 overflow-auto whitespace-pre-wrap font-mono leading-relaxed min-h-[360px]">
              {output}
            </pre>
            <div className="mt-4 bg-[#0A0A14] rounded-xl p-3">
              <p className="text-xs text-gray-500 font-semibold mb-1">📋 Next Steps</p>
              <ol className="text-xs text-gray-500 space-y-1 list-decimal list-inside">
                <li>Download and upload <code className="text-cyan-400">sitemap.xml</code> to your website root</li>
                <li>Add <code className="text-cyan-400">Sitemap: {domain || "https://yoursite.com"}/sitemap.xml</code> to robots.txt</li>
                <li>Submit the URL in <a href="https://search.google.com/search-console" target="_blank" rel="noopener noreferrer" className="text-[#6C3AFF] hover:underline">Google Search Console</a></li>
              </ol>
            </div>
          </div>
        </div>

      </main>

      <footer className="border-t border-white/5 mt-16 py-8 text-center">
        <Link href="/" className="text-xl font-black">Purs<span className="text-[#6C3AFF]">Tech</span></Link>
        <div className="flex justify-center gap-6 mt-3 text-xs text-gray-600">
          <Link href="/about"   className="hover:text-gray-400 transition-colors">About</Link>
          <Link href="/privacy" className="hover:text-gray-400 transition-colors">Privacy</Link>
          <Link href="/contact" className="hover:text-gray-400 transition-colors">Contact</Link>
        </div>
        <p className="text-gray-700 text-xs mt-3">© 2025 PursTech. All rights reserved.</p>
      </footer>
    </div>
  );
}
