"use client";

import { useState } from "react";
import Link from "next/link";

interface MetaFields {
  title:          string;
  description:    string;
  author:         string;
  robots:         string;
  viewport:       string;
  charset:        string;
  ogTitle:        string;
  ogDescription:  string;
  ogImage:        string;
  ogUrl:          string;
  ogType:         string;
  ogSiteName:     string;
  twitterCard:    string;
  twitterTitle:   string;
  twitterDesc:    string;
  twitterImage:   string;
  twitterHandle:  string;
}

const DEFAULTS: MetaFields = {
  title:          "",
  description:    "",
  author:         "",
  robots:         "index, follow",
  viewport:       "width=device-width, initial-scale=1.0",
  charset:        "UTF-8",
  ogTitle:        "",
  ogDescription:  "",
  ogImage:        "",
  ogUrl:          "",
  ogType:         "website",
  ogSiteName:     "",
  twitterCard:    "summary_large_image",
  twitterTitle:   "",
  twitterDesc:    "",
  twitterImage:   "",
  twitterHandle:  "",
};

function charCount(val: string, max: number) {
  const over = val.length > max;
  return (
    <span className={`text-xs ${over ? "text-[#FF3A6C]" : "text-gray-500"}`}>
      {val.length}/{max}
    </span>
  );
}

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block text-sm font-semibold text-white mb-1">{label}</label>
      {hint && <p className="text-xs text-gray-500 mb-1.5">{hint}</p>}
      {children}
    </div>
  );
}

function Input({ value, onChange, placeholder, maxLen }: {
  value: string; onChange: (v: string) => void;
  placeholder?: string; maxLen?: number;
}) {
  return (
    <div>
      <input value={value} onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
      {maxLen && <div className="flex justify-end mt-1">{charCount(value, maxLen)}</div>}
    </div>
  );
}

function Select({ value, onChange, options }: {
  value: string; onChange: (v: string) => void;
  options: { label: string; value: string }[];
}) {
  return (
    <select value={value} onChange={e => onChange(e.target.value)}
      className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm focus:outline-none focus:border-[#6C3AFF]/60 transition-all">
      {options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
    </select>
  );
}

export default function MetaTagGeneratorClient() {
  const [fields, setFields] = useState<MetaFields>(DEFAULTS);
  const [copied, setCopied] = useState(false);
  const [tab, setTab]       = useState<"basic" | "og" | "twitter">("basic");

  const set = (k: keyof MetaFields) => (v: string) =>
    setFields(prev => ({ ...prev, [k]: v }));

  const syncFields = (k: keyof MetaFields, v: string) => {
    setFields(prev => {
      const next = { ...prev, [k]: v };
      if (k === "title") {
        if (!prev.ogTitle)      next.ogTitle      = v;
        if (!prev.twitterTitle) next.twitterTitle = v;
      }
      if (k === "description") {
        if (!prev.ogDescription) next.ogDescription = v;
        if (!prev.twitterDesc)   next.twitterDesc   = v;
      }
      return next;
    });
  };

  function generateTags(): string {
    const lines: string[] = ["<!-- Generated by PursTech Meta Tag Generator -->", "<!-- Basic SEO -->"];
    if (fields.charset)     lines.push(`<meta charset="${fields.charset}">`);
    if (fields.viewport)    lines.push(`<meta name="viewport" content="${fields.viewport}">`);
    if (fields.title)       lines.push(`<title>${fields.title}</title>`);
    if (fields.description) lines.push(`<meta name="description" content="${fields.description}">`);
    if (fields.author)      lines.push(`<meta name="author" content="${fields.author}">`);
    if (fields.robots)      lines.push(`<meta name="robots" content="${fields.robots}">`);

    if (fields.ogTitle || fields.ogDescription || fields.ogImage) {
      lines.push("", "<!-- Open Graph / Social -->",
        `<meta property="og:type" content="${fields.ogType}">`);
      if (fields.ogUrl)         lines.push(`<meta property="og:url" content="${fields.ogUrl}">`);
      if (fields.ogTitle)       lines.push(`<meta property="og:title" content="${fields.ogTitle}">`);
      if (fields.ogDescription) lines.push(`<meta property="og:description" content="${fields.ogDescription}">`);
      if (fields.ogImage)       lines.push(`<meta property="og:image" content="${fields.ogImage}">`);
      if (fields.ogSiteName)    lines.push(`<meta property="og:site_name" content="${fields.ogSiteName}">`);
    }

    if (fields.twitterCard) {
      lines.push("", "<!-- Twitter / X Card -->",
        `<meta name="twitter:card" content="${fields.twitterCard}">`);
      if (fields.twitterHandle) lines.push(`<meta name="twitter:site" content="${fields.twitterHandle}">`);
      if (fields.twitterTitle)  lines.push(`<meta name="twitter:title" content="${fields.twitterTitle}">`);
      if (fields.twitterDesc)   lines.push(`<meta name="twitter:description" content="${fields.twitterDesc}">`);
      if (fields.twitterImage)  lines.push(`<meta name="twitter:image" content="${fields.twitterImage}">`);
    }

    return lines.join("\n");
  }

  const output = generateTags();

  function copy() {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function reset() { setFields(DEFAULTS); }

  const tabs = [
    { id: "basic",   label: "🔍 Basic SEO"   },
    { id: "og",      label: "📘 Open Graph"  },
    { id: "twitter", label: "𝕏 Twitter Card" },
  ] as const;

  return (
    <div className="min-h-screen bg-[#0A0A14] text-white font-sans">
      <nav className="border-b border-white/5 px-4 py-4 sticky top-0 bg-[#0A0A14]/95 backdrop-blur-md z-40">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-xl font-black">Purs<span className="text-[#6C3AFF]">Tech</span></Link>
          <div className="flex items-center gap-4">
            <Link href="/tools" className="text-sm text-gray-500 hover:text-white transition-colors">All Tools</Link>
            <Link href="/blog"  className="text-sm text-gray-500 hover:text-white transition-colors">Blog</Link>
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 py-10">
        <nav className="text-xs text-gray-600 mb-6 flex items-center gap-2">
          <Link href="/" className="hover:text-gray-400 transition-colors">Home</Link>
          <span>›</span>
          <Link href="/tools" className="hover:text-gray-400 transition-colors">Tools</Link>
          <span>›</span>
          <span className="text-gray-400">Meta Tag Generator</span>
        </nav>

        <div className="mb-8">
          <div className="inline-flex items-center gap-2 bg-[#6C3AFF]/10 border border-[#6C3AFF]/20 rounded-full px-3 py-1 text-xs text-[#6C3AFF] font-semibold mb-3">
            SEO Tools
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-3">
            Free Online Meta Tag Generator
          </h1>
          <p className="text-gray-400 max-w-2xl">
            Generate perfectly optimized HTML meta tags for SEO, Open Graph and Twitter Cards in seconds. Copy and paste directly into your website's <code className="text-cyan-400 bg-[#13131F] px-1 rounded">&lt;head&gt;</code>.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-12">
          {/* Left — Inputs */}
          <div className="bg-[#13131F] border border-white/5 rounded-2xl p-6">
            <div className="flex gap-1 bg-[#0A0A14] p-1 rounded-xl mb-6">
              {tabs.map(t => (
                <button key={t.id} onClick={() => setTab(t.id)}
                  className={`flex-1 py-2 px-3 rounded-lg text-xs font-bold transition-all ${
                    tab === t.id
                      ? "bg-[#6C3AFF] text-white shadow"
                      : "text-gray-400 hover:text-white"
                  }`}>
                  {t.label}
                </button>
              ))}
            </div>

            {tab === "basic" && (
              <div className="space-y-4">
                <Field label="Page Title" hint="50–60 characters recommended">
                  <Input value={fields.title} onChange={v => syncFields("title", v)}
                    placeholder="My Awesome Page Title" maxLen={60} />
                </Field>
                <Field label="Meta Description" hint="150–160 characters recommended">
                  <div>
                    <textarea value={fields.description}
                      onChange={e => syncFields("description", e.target.value)}
                      rows={3} placeholder="A compelling description of this page..."
                      className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all resize-none" />
                    <div className="flex justify-end">{charCount(fields.description, 160)}</div>
                  </div>
                </Field>
                <Field label="Author">
                  <Input value={fields.author} onChange={set("author")} placeholder="PursTech Team" />
                </Field>
                <Field label="Robots">
                  <Select value={fields.robots} onChange={set("robots")} options={[
                    { label: "index, follow",         value: "index, follow"         },
                    { label: "noindex, follow",       value: "noindex, follow"       },
                    { label: "index, nofollow",       value: "index, nofollow"       },
                    { label: "noindex, nofollow",     value: "noindex, nofollow"     },
                  ]} />
                </Field>
              </div>
            )}

            {tab === "og" && (
              <div className="space-y-4">
                <Field label="OG Title" hint="Usually same as page title">
                  <Input value={fields.ogTitle} onChange={set("ogTitle")} placeholder="My Awesome Page" maxLen={60} />
                </Field>
                <Field label="OG Description" hint="Usually same as meta description">
                  <div>
                    <textarea value={fields.ogDescription}
                      onChange={e => set("ogDescription")(e.target.value)}
                      rows={3} placeholder="Page description for social sharing..."
                      className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all resize-none" />
                    <div className="flex justify-end">{charCount(fields.ogDescription, 160)}</div>
                  </div>
                </Field>
                <Field label="OG Image URL" hint="Recommended: 1200×630px">
                  <Input value={fields.ogImage} onChange={set("ogImage")} placeholder="https://yoursite.com/og-image.png" />
                </Field>
                <Field label="Page URL">
                  <Input value={fields.ogUrl} onChange={set("ogUrl")} placeholder="https://yoursite.com/page" />
                </Field>
                <Field label="Site Name">
                  <Input value={fields.ogSiteName} onChange={set("ogSiteName")} placeholder="YourSite" />
                </Field>
                <Field label="Content Type">
                  <Select value={fields.ogType} onChange={set("ogType")} options={[
                    { label: "website", value: "website" },
                    { label: "article", value: "article" },
                    { label: "product", value: "product" },
                    { label: "profile", value: "profile" },
                  ]} />
                </Field>
              </div>
            )}

            {tab === "twitter" && (
              <div className="space-y-4">
                <Field label="Card Type">
                  <Select value={fields.twitterCard} onChange={set("twitterCard")} options={[
                    { label: "Summary with Large Image", value: "summary_large_image" },
                    { label: "Summary",                  value: "summary"             },
                    { label: "App",                      value: "app"                 },
                  ]} />
                </Field>
                <Field label="Twitter Title">
                  <Input value={fields.twitterTitle} onChange={set("twitterTitle")} placeholder="My Awesome Page" maxLen={70} />
                </Field>
                <Field label="Twitter Description">
                  <div>
                    <textarea value={fields.twitterDesc}
                      onChange={e => set("twitterDesc")(e.target.value)}
                      rows={3} placeholder="Description for Twitter card..."
                      className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all resize-none" />
                    <div className="flex justify-end">{charCount(fields.twitterDesc, 200)}</div>
                  </div>
                </Field>
                <Field label="Twitter Image URL">
                  <Input value={fields.twitterImage} onChange={set("twitterImage")} placeholder="https://yoursite.com/twitter-card.png" />
                </Field>
                <Field label="Twitter Handle" hint="Your @username">
                  <Input value={fields.twitterHandle} onChange={set("twitterHandle")} placeholder="@yoursite" />
                </Field>
              </div>
            )}
          </div>

          {/* Right — Output */}
          <div className="flex flex-col gap-4">
            {/* Live Preview */}
            <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5">
              <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">
                {tab === "basic" ? "Google Search Preview" : tab === "og" ? "Facebook / LinkedIn Preview" : "Twitter / X Preview"}
              </h3>
              
              {tab === "basic" && (
                <div className="bg-white rounded-xl p-4">
                  <div className="text-xs text-[#202124] mb-1 flex items-center gap-2 truncate">
                    <span className="w-4 h-4 bg-gray-200 rounded-full inline-block"></span>
                    https://yoursite.com
                  </div>
                  <div className="text-[#1a0dab] text-xl font-normal leading-snug mb-1 truncate hover:underline cursor-pointer">
                    {fields.title || "Your Page Title Goes Here"}
                  </div>
                  <div className="text-[#4d5156] text-sm leading-[1.58] line-clamp-2">
                    {fields.description || "Your meta description will appear here. Write something compelling to increase click-through rates from Google search results."}
                  </div>
                </div>
              )}

              {tab === "og" && (
                 <div className="bg-[#F0F2F5] rounded-xl overflow-hidden shadow-sm">
                 {fields.ogImage ? (
                   <img src={fields.ogImage} alt="OG Preview" className="w-full h-40 object-cover"
                     onError={e => { (e.target as HTMLImageElement).style.display = "none"; }} />
                 ) : (
                   <div className="w-full h-40 bg-gray-300 flex items-center justify-center text-gray-500 text-sm font-medium border-b border-gray-200">
                     1200×630 Image Preview
                   </div>
                 )}
                 <div className="p-3 bg-[#f2f3f5] border-t border-gray-300">
                   <div className="text-[12px] text-[#65676B] uppercase tracking-wide mb-0.5 truncate">{fields.ogUrl ? fields.ogUrl.replace(/^https?:\/\//, "").split("/")[0] : "yoursite.com"}</div>
                   <div className="font-semibold text-[#050505] text-[16px] leading-tight line-clamp-1 mb-0.5">{fields.ogTitle || "Your Page Title"}</div>
                   <div className="text-[14px] text-[#65676B] leading-snug line-clamp-1">{fields.ogDescription || "Your page description will appear here when shared."}</div>
                 </div>
               </div>
              )}

              {tab === "twitter" && (
                 <div className="bg-black rounded-xl border border-gray-800 overflow-hidden">
                 {fields.twitterImage ? (
                   <img src={fields.twitterImage} alt="Twitter Preview" className="w-full h-40 object-cover border-b border-gray-800"
                     onError={e => { (e.target as HTMLImageElement).style.display = "none"; }} />
                 ) : (
                   <div className="w-full h-40 bg-gray-900 flex items-center justify-center text-gray-500 text-sm border-b border-gray-800">
                     Twitter Card Image
                   </div>
                 )}
                 <div className="p-3">
                   <div className="text-gray-500 text-sm mb-0.5 truncate">{fields.twitterHandle || "yoursite.com"}</div>
                   <div className="font-bold text-white text-[15px] leading-tight line-clamp-1 mb-1">{fields.twitterTitle || "Your Page Title"}</div>
                   <div className="text-[15px] text-gray-500 leading-snug line-clamp-2">{fields.twitterDesc || "Description for Twitter card..."}</div>
                 </div>
               </div>
              )}
            </div>

            {/* Generated Code */}
            <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5 flex-1 flex flex-col">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider">
                  Generated HTML
                </h3>
                <div className="flex gap-2">
                  <button onClick={reset}
                    className="px-3 py-1.5 rounded-lg bg-[#0A0A14] border border-white/10 text-gray-400 hover:text-white text-xs transition-all">
                    Reset
                  </button>
                  <button onClick={copy}
                    className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                      copied ? "bg-green-600 text-white" : "bg-[#6C3AFF] hover:bg-[#5B2EE0] text-white"
                    }`}>
                    {copied ? "✓ Copied!" : "Copy Code"}
                  </button>
                </div>
              </div>
              <pre className="flex-1 text-xs text-green-400 bg-[#0A0A14] rounded-xl p-4 overflow-auto whitespace-pre-wrap font-mono leading-relaxed min-h-[320px]">
                {output}
              </pre>
            </div>
          </div>
        </div>

        {/* How to use */}
        <div className="mb-12 bg-[#13131F] border border-white/5 rounded-2xl p-8">
          <h2 className="text-xl font-extrabold text-white mb-6">How to Use the Meta Tag Generator</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-sm text-gray-400">
            {[
              { step: "1", title: "Fill in the Basics", desc: "Start with the Basic SEO tab. Enter your core page title and description. Watch the live Google SERP preview to ensure your text isn't truncated." },
              { step: "2", title: "Configure Social Cards", desc: "Switch to the Open Graph and Twitter tabs. Our tool automatically syncs your basic info, so you only need to add your image URLs and specific social handles." },
              { step: "3", title: "Copy & Paste HTML", desc: "Click the 'Copy Code' button. Paste the generated HTML tags directly into the <head> section of your website's code before the closing </head> tag." },
            ].map(s => (
              <div key={s.step} className="flex gap-4">
                <div className="w-8 h-8 rounded-full bg-[#6C3AFF]/20 text-[#6C3AFF] border border-[#6C3AFF]/30 flex items-center justify-center font-bold flex-shrink-0">
                  {s.step}
                </div>
                <div>
                  <div className="font-bold text-white mb-1.5 text-base">{s.title}</div>
                  <div className="leading-relaxed">{s.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
