"use client";

import { useState } from "react";
import Link from "next/link";

interface Rule {
  id:       number;
  agent:    string;
  allow:    string;
  disallow: string;
}

let nextId = 1;

const PRESETS: Record<string, Rule[]> = {
  "Standard Blog": [
    { id: nextId++, agent: "*", allow: "", disallow: "/wp-admin/" },
    { id: nextId++, agent: "*", allow: "", disallow: "/wp-includes/" },
    { id: nextId++, agent: "*", allow: "", disallow: "/?s=" },
  ],
  "E-Commerce": [
    { id: nextId++, agent: "*", allow: "", disallow: "/cart/" },
    { id: nextId++, agent: "*", allow: "", disallow: "/checkout/" },
    { id: nextId++, agent: "*", allow: "", disallow: "/account/" },
    { id: nextId++, agent: "*", allow: "", disallow: "/search" },
  ],
  "Block All": [
    { id: nextId++, agent: "*", allow: "", disallow: "/" },
  ],
  "Allow All": [
    { id: nextId++, agent: "*", allow: "/", disallow: "" },
  ],
};

export default function RobotsTxtClient() {
  const [rules, setRules]           = useState<Rule[]>([
    { id: nextId++, agent: "*", allow: "", disallow: "/admin/" },
  ]);
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [crawlDelay, setCrawlDelay] = useState("");
  const [copied, setCopied]         = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  function addRule() {
    setRules(prev => [...prev, { id: nextId++, agent: "*", allow: "", disallow: "" }]);
  }

  function removeRule(id: number) {
    setRules(prev => prev.filter(r => r.id !== id));
  }

  function updateRule(id: number, field: keyof Omit<Rule, "id">, value: string) {
    setRules(prev => prev.map(r => r.id === id ? { ...r, [field]: value } : r));
  }

  function applyPreset(name: string) {
    setRules(PRESETS[name].map(r => ({ ...r, id: nextId++ })));
  }

  function generateRobots(): string {
    // Group rules by user-agent
    const byAgent: Record<string, { allow: string[]; disallow: string[] }> = {};
    rules.forEach(rule => {
      if (!byAgent[rule.agent]) byAgent[rule.agent] = { allow: [], disallow: [] };
      if (rule.allow.trim())    byAgent[rule.agent].allow.push(rule.allow.trim());
      if (rule.disallow.trim()) byAgent[rule.agent].disallow.push(rule.disallow.trim());
    });

    const lines = ["# Generated by PursTech Robots.txt Generator", "# https://purstech.com/tools/robots-txt-generator", ""];

    Object.entries(byAgent).forEach(([agent, { allow, disallow }]) => {
      lines.push(`User-agent: ${agent}`);
      if (crawlDelay) lines.push(`Crawl-delay: ${crawlDelay}`);
      disallow.forEach(p => lines.push(`Disallow: ${p}`));
      allow.forEach(p => lines.push(`Allow: ${p}`));
      lines.push("");
    });

    if (sitemapUrl.trim()) {
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    return lines.join("\n").trim();
  }

  const output = generateRobots();

  function copy() {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function download() {
    const blob = new Blob([output], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2000);
  }

  const agentOptions = [
    { label: "All bots (*)",     value: "*"          },
    { label: "Googlebot",        value: "Googlebot"  },
    { label: "Bingbot",          value: "Bingbot"    },
    { label: "GPTBot (ChatGPT)", value: "GPTBot"     },
    { label: "ClaudeBot",        value: "ClaudeBot"  },
    { label: "AhrefsBot",        value: "AhrefsBot"  },
    { label: "SemrushBot",       value: "SemrushBot" },
  ];

  return (
    <div className="min-h-screen bg-[#0A0A14] text-white font-sans">

      <nav className="border-b border-white/5 px-4 py-4 sticky top-0 bg-[#0A0A14]/95 backdrop-blur-md z-40">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-xl font-black">Purs<span className="text-[#6C3AFF]">Tech</span></Link>
          <Link href="/tools" className="text-sm text-gray-500 hover:text-white transition-colors">All Tools</Link>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 py-10">

        <nav className="text-xs text-gray-600 mb-6 flex items-center gap-2">
          <Link href="/" className="hover:text-gray-400 transition-colors">Home</Link>
          <span>›</span>
          <Link href="/tools" className="hover:text-gray-400 transition-colors">Tools</Link>
          <span>›</span>
          <span className="text-gray-400">Robots.txt Generator</span>
        </nav>

        <div className="mb-8">
          <div className="inline-flex items-center gap-2 bg-[#6C3AFF]/10 border border-[#6C3AFF]/20 rounded-full px-3 py-1 text-xs text-[#6C3AFF] font-semibold mb-3">
            SEO Tools
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-3">
            Free Robots.txt Generator Online
          </h1>
          <p className="text-gray-400 max-w-2xl">
            Create a valid robots.txt file for your website in seconds. Control which pages search engines can crawl, block unwanted bots, and add your sitemap URL.
          </p>
        </div>

        {/* Presets */}
        <div className="mb-6">
          <p className="text-xs text-gray-500 font-semibold uppercase tracking-wider mb-2">Quick Presets</p>
          <div className="flex flex-wrap gap-2">
            {Object.keys(PRESETS).map(name => (
              <button key={name} onClick={() => applyPreset(name)}
                className="px-4 py-2 rounded-xl bg-[#13131F] border border-white/5 hover:border-[#6C3AFF]/40 text-sm text-gray-400 hover:text-white transition-all">
                {name}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

          {/* Left — Rule builder */}
          <div className="space-y-4">

            {/* Rules */}
            <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-white text-sm">Crawler Rules</h3>
                <button onClick={addRule}
                  className="px-3 py-1.5 rounded-lg bg-[#6C3AFF] hover:bg-[#5B2EE0] text-white text-xs font-bold transition-all">
                  + Add Rule
                </button>
              </div>

              <div className="space-y-3">
                {rules.map(rule => (
                  <div key={rule.id} className="bg-[#0A0A14] rounded-xl p-3 border border-white/5">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs text-gray-500 font-semibold">User-agent</span>
                      <button onClick={() => removeRule(rule.id)}
                        className="text-gray-600 hover:text-[#FF3A6C] text-xs transition-colors">
                        × Remove
                      </button>
                    </div>
                    <select value={rule.agent}
                      onChange={e => updateRule(rule.id, "agent", e.target.value)}
                      className="w-full px-3 py-2 rounded-lg bg-[#13131F] border border-white/10 text-white text-sm focus:outline-none focus:border-[#6C3AFF]/60 transition-all mb-2">
                      {agentOptions.map(o => (
                        <option key={o.value} value={o.value}>{o.label}</option>
                      ))}
                    </select>
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <label className="text-xs text-red-400 font-semibold mb-1 block">Disallow</label>
                        <input value={rule.disallow}
                          onChange={e => updateRule(rule.id, "disallow", e.target.value)}
                          placeholder="/admin/"
                          className="w-full px-3 py-2 rounded-lg bg-[#13131F] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
                      </div>
                      <div>
                        <label className="text-xs text-green-400 font-semibold mb-1 block">Allow</label>
                        <input value={rule.allow}
                          onChange={e => updateRule(rule.id, "allow", e.target.value)}
                          placeholder="/public/"
                          className="w-full px-3 py-2 rounded-lg bg-[#13131F] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Sitemap + Crawl Delay */}
            <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5 space-y-4">
              <div>
                <label className="block text-sm font-semibold text-white mb-1">Sitemap URL</label>
                <input value={sitemapUrl} onChange={e => setSitemapUrl(e.target.value)}
                  placeholder="https://yoursite.com/sitemap.xml"
                  className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
              </div>
              <div>
                <label className="block text-sm font-semibold text-white mb-1">Crawl Delay (seconds)</label>
                <input value={crawlDelay} onChange={e => setCrawlDelay(e.target.value)}
                  placeholder="10" type="number" min="0"
                  className="w-full px-4 py-2.5 rounded-xl bg-[#0A0A14] border border-white/10 text-white text-sm placeholder-gray-600 focus:outline-none focus:border-[#6C3AFF]/60 transition-all" />
              </div>
            </div>
          </div>

          {/* Right — Output */}
          <div className="bg-[#13131F] border border-white/5 rounded-2xl p-5 flex flex-col">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider">robots.txt</h3>
              <div className="flex gap-2">
                <button onClick={copy}
                  className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    copied ? "bg-green-600 text-white" : "bg-[#13131F] border border-white/10 text-gray-400 hover:text-white"
                  }`}>
                  {copied ? "✓ Copied!" : "Copy"}
                </button>
                <button onClick={download}
                  className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    downloaded ? "bg-green-600 text-white" : "bg-[#6C3AFF] hover:bg-[#5B2EE0] text-white"
                  }`}>
                  {downloaded ? "✓ Saved!" : "⬇ Download"}
                </button>
              </div>
            </div>
            <pre className="flex-1 text-xs text-green-400 bg-[#0A0A14] rounded-xl p-4 overflow-auto whitespace-pre-wrap font-mono leading-relaxed min-h-[400px]">
              {output}
            </pre>
            <p className="text-xs text-gray-600 mt-3">
              📁 Upload as <code className="text-cyan-400">robots.txt</code> to your website root (e.g. <code className="text-cyan-400">yoursite.com/robots.txt</code>)
            </p>
          </div>
        </div>

      </main>

      <footer className="border-t border-white/5 mt-16 py-8 text-center">
        <Link href="/" className="text-xl font-black">Purs<span className="text-[#6C3AFF]">Tech</span></Link>
        <div className="flex justify-center gap-6 mt-3 text-xs text-gray-600">
          <Link href="/about"   className="hover:text-gray-400 transition-colors">About</Link>
          <Link href="/privacy" className="hover:text-gray-400 transition-colors">Privacy</Link>
          <Link href="/contact" className="hover:text-gray-400 transition-colors">Contact</Link>
        </div>
        <p className="text-gray-700 text-xs mt-3">© 2025 PursTech. All rights reserved.</p>
      </footer>
    </div>
  );
}
